version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: group10_database
      MYSQL_USER: group10
      MYSQL_PASSWORD: group10password
      MYSQL_ROOT_PASSWORD: group10password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: group10password
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: